import Head from 'next/head';
import Login from './login';
import UserSearch from './user/search';
import { useAuth } from '../context/AuthContext';

export default function Home() {
  const { currentUser } = useAuth();
  return (
    <>
      <Head>
        <title>Lovyca</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!currentUser && <Login />}
      {currentUser && <UserSearch />}
    </>
  );
}
